apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-runtime-scheduler
  namespace: default
  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cron-runtime-scheduler-role
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "create" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-runtime-scheduler-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cron-runtime-scheduler
    namespace: default
roleRef:
  kind: Role
  name: cron-runtime-scheduler-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-runtime-scheduler
  labels:
    app: cron-runtime-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-runtime-scheduler
  template:
    metadata:
      labels:
        app: cron-runtime-scheduler
    spec:
      serviceAccountName: cron-runtime-scheduler
      containers:
        - name: scheduler
          image: cron-sceduler:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
